
services:
  web:
    image: flask-container  # Use the pre-built image
    ports:
      - "8080:8080"
    environment:
      - FLASK_APP=backend/app.py
      - FLASK_ENV=production
      - PYTHONPATH=/app
      - NODE_ENV=production
      - CI=false
      - GENERATE_SOURCEMAP=false
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./.env:/app/.env:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 