services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: builder
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - voice

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=production
    volumes:
      - ./backend:/app
      - vosk-models:/app/models

  voice:
    build:
      context: ./backend/voice
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - CGO_ENABLED=1
    volumes:
      - ./backend/voice:/app

volumes:
  vosk-models: 