services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - NODE_ENV=development
      
    ports:
      - "8080:8080"
    environment:
      - FLASK_APP=backend/app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONPATH=/app
      - NODE_ENV=development
      - CI=false
      - GENERATE_SOURCEMAP=false
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./backend:/app/backend
      - ./.env:/app/.env:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge